### ISSUE TITLE
Release 1.1 Checklist

### ISSUE THREAD

**Issue by Igorbek** [Igorbek/typescript-plugin-styled-components#25]
- [ ] fix duplicate component id generation
- [ ] update README
- [ ] document new options
- [ ] add automated build for publishing
